#!/usr/bin/python

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

sum_of_nums = 0
n = 1
k = 2

while k <=4000000: #k is the larger number
	if k % 2 == 0: #looks if k or n is even
		sum_of_nums += k
	elif n % 2 == 0:
		sum_of_nums += n 
	n = n + k #go 1 step to the right in the fibonacci sequence
	k = n + k

print(sum_of_nums)
